### ISSUE TITLE
APK availability

### ISSUE THREAD

**Issue by IzzySoft** [w2sv/WiFi-Widget#1]
First a big thanks for making your app available F/LOSS under a libre license! Would you also consider making the APK available outside Google's walled garden, for those who have no access to it? Easiest way would be attaching it to the corresponding [release](https://github.com/w2sv/WiFi-Widget/releases). Thanks in advance!

**Comment by w2sv** [comment]
Sure, down with Google's walled garden walls! I attached the respective APK's to the last two releases.

**Comment by IzzySoft** [comment]
Coolest answer ever :star_struck: Let me take down the walls on the other end then, too: with the next sync around 7 pm UTC today (gegen 20 Uhr) your app should [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.w2sv.wifiwidget). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to accompany the one of the garden and linking there. Folks with an F-Droid client using my repo can now easily discover your app, install it and keep it updated automatically (my update checker runs once a day to look for new tags and grab the APK attached to them if found). Preview:
![image](https://user-images.githubusercontent.com/6781438/216618290-bf624ba2-c6eb-4c57-b937-30f938db9b79.png)

Should you wish to proceed to the [F-Droid](https://f-droid.org/) repo, your app seems to meet the inclusion criteria there. Let me know if you need any assistance with that, and I gladly get you started with that step.

Und beste Grüße nach Dresden! :smiley:

**Comment by w2sv** [comment]
Thank you for providing all of that information, I added the badges to the README, where they're now doing an absolutely marvelous job in accompanying the wally ones in my modest opinion.
Yes, I think I'll try to publish it on F-Droid as well, I'll give it a shot as soon as I find time for it. Thank you for the offered help.

Beste Grüße zurück nach München :)

**Comment by IzzySoft** [comment]
That leaves not much to say for me – I'll miss your wonderful responses! :star_struck: :cry: Meet you again "over there" then once you've started your RFP. And maybe one day in Dresden (where I have family) or München!
