### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by Welforj** [w2sv/WiFi-Widget#100]
Labels aren't displaying correctly font is only 50% showing 
![Screenshot_20240216-055714](https://github.com/w2sv/WiFi-Widget/assets/96409939/2a3241a0-59c0-4b3d-b634-7f5509e9a076)

**Comment by w2sv** [comment]
What Android version and phone is that?

**Comment by Welforj** [comment]
Android 14. Love the widget by the way. Thank you

**Comment by w2sv** [comment]
Should be fixed in [1.4.10](https://github.com/w2sv/WiFi-Widget/releases/tag/1.4.10).
