### ISSUE TITLE
Frequency order of magnitude error 

### ISSUE THREAD

**Issue by ShrirajHegde** [w2sv/WiFi-Widget#11]
There seems to be an error with the order of magnitude of band frequency. For me it's being reported as 2.4 KHz instead of 2.4GHz.

![Screenshot_2023-03-10-00-55-19-342_com.teslacoilsw.launcher.png](https://user-images.githubusercontent.com/66936172/224133238-db3bbf9f-569c-4384-b9cd-3eb0ee2c9dc0.png)

**Comment by w2sv** [comment]
Good catch, I'll fix that first thing tomorrow. Thanks for reporting.

**Comment by w2sv** [comment]
Aight, it's fixed in [1.1.8](https://github.com/w2sv/WiFi-Widget/releases/tag/1.1.8).
