### ISSUE TITLE
[Bug] Custom Colours Restore Back To Default After System Cache Clear In MIUI.

### ISSUE THREAD

**Issue by atikattar1104** [w2sv/WiFi-Widget#119]
### Overview

After Cleaning System Cache Using Its Own Widget, Or Using System Security App In MIUI, The Widget Restores Back To Default Colour Scheme. 

Sometimes, Colour Stay As Assigned After Clearing Cache, Until Refreshed. In This Second Senario, As Soon As We Refresh Widget, It Restores Back To Default Colour Scheme. 

Workaround To Both Of These, Is You Have To Refresh Widget Several Times, Until All Texts And Background Colours Are Reassigned As User Defined Settings.

### How to reproduce

1. Create Widget With Custom Colour Scheme.
2. Clear System Cache.
3. See Error.

### Version

v1.4.11

### Android Version

Android 10, MIUI 12.5

### Device Model

Redmi 7A

**Comment by w2sv** [comment]
For me it even suffices to merely remove the app from the 'recents' back stack. I'm quite baffled by that, that's definitely a huge bug. Will look directly into that.

**Comment by w2sv** [comment]
Fixed in [1.4.13](https://github.com/w2sv/WiFi-Widget/releases/tag/1.4.13), let me know if it works for you. Thanks for reporting!

**Comment by atikattar1104** [comment]
Great! Although, I May Need To Wait Since F-Droid Has To Update This App As Well.

**Comment by w2sv** [comment]
If you trust me you can get the apk from the release page I've linked too, otherwise you'll have to wait, yeah :)

**Comment by atikattar1104** [comment]
![Screenshot_2024-04-17-22-34-53-641_com miui home](https://github.com/w2sv/WiFi-Widget/assets/93785261/34ddb32e-4eda-4630-bef0-0fef09c36ef6)

The Internal Text Colour Is Now Not Reverting Back To Default Colour. Now Just Remains The Background Opacity And Lower Panel Text And Icon Colour Reverting Back To Default.

**Comment by w2sv** [comment]
Have you tried it with a new widget, or is it one from before the update?

**Comment by w2sv** [comment]
The post-update RemoteViewsService, which is responsible for the WiFi property views, might not have connected to the pre-update widget

**Comment by atikattar1104** [comment]
Tried With Both. Same Result. Also, I Thought I Might Get APK Signature Issue, But APK Installation From Release Worked.

**Comment by atikattar1104** [comment]
But The Colour Of Inside Text Remains Intact Just As Expected.

**Comment by w2sv** [comment]
What are the appearance settings corresponding to the widget on the screenshot? I didn't quite get that.

**Comment by atikattar1104** [comment]
![Screenshot_2024-04-17-23-15-02-031_com w2sv wifiwidget](https://github.com/w2sv/WiFi-Widget/assets/93785261/f006c214-93c2-4ea7-acc2-34d181f922db)

**Comment by atikattar1104** [comment]
Tried By Changing Alpha Value In Background Colour, But Still Same Result.

**Comment by atikattar1104** [comment]
End Goal Is As Same As Nearby Widgets.

**Comment by atikattar1104** [comment]
Sure. Also, Let Me Know If I Can Help. Would Love To Test More Features In Future.

**Comment by w2sv** [comment]
Please give https://github.com/w2sv/WiFi-Widget/releases/tag/1.4.14-rc1 a try and lmk if the bug is resolved :)

**Comment by atikattar1104** [comment]
Cannot Create Bug Anymore, Means Fixed Entirely. Great! Closing This Issue.
