### ISSUE TITLE
[Feature Request] Display Subnet Mask, Signal Strength, Status, Technology, Security

### ISSUE THREAD

**Issue by atikattar1104** [w2sv/WiFi-Widget#120]
### Overview

For Example, 

Subnet Mask Of Wifi :- 255.255.255.0, 255.255.255.10, Etc.
Signal Strength :- Excellent, Good, Poor, Etc.
Status :- "Connected", "Connected, No Internet", Etc.
Technology :- Wifi 4, Wifi 6, Etc.
Security :- WPA, WPA 2, WPA 2 PSK, WEP, Etc.

These All Data Is Visible In Wifi Settings.

**Comment by w2sv** [comment]
I've added the signal strength, technology (under the name WiFi generation) and security in 1.5.01. The WiFi status is redundant, as the widget will display "No WiFi connection" on "Connected, no internet", the subnet masks I'll maybe add in another release. They are already indirectly represented through the prefix length accompanying (almost) each IP property, if I wanted to add them anyways though, I'd correspondingly have to add them to each IP property, too. I'll create a separate issue for that. Thank you for the request.

**Comment by atikattar1104** [comment]
Great. Sorry I Had No Time Because Of My Exams. I Agree With Wifi Status. It May Not Be Necessary. 

I Also Saw Your Response On `Pseudo Data And Keep Widget On` Issue. I Just Figured On About Keeping Widget On One, Didn't Thought That Through😅. And For Pseudo Data One, It Can Be Hefty Work For Both Development As Well As Pseudo Data Definition From User Side. 

Looking Forward For Furthur Releases👍.
