### ISSUE TITLE
[Feature Request] Display Pseudo Data And Keep Widget On Even If Wifi Off.

### ISSUE THREAD

**Issue by atikattar1104** [w2sv/WiFi-Widget#126]
### Overview

1) The Pseudo Data Is Useful If User Wants To Stream Screen And Doesn't Want To Display Sensitive Data On It, While Keeping Widget Active.

2) The `Keep Widget On Even If Wifi Off` Can Be Useful If User's Device Battery Is Consumed By Wifi Usage And Wants To Turn Off Wifi For Battery Health. This Can Also Help If A User Wants To Avoid Being Visible On Wifi, But Also Keep Widget On.

**Comment by w2sv** [comment]
Interesting propositions, however for the first one, wouldn't it be way easier to just remove the widget and pin a new one after finishing screen sharing, than open the app, click on some hypothetical 'show pseudo data' button in the widget configuration dialog, and afterwards do the same again to deactivate the pseudo data display? Or maybe it's not necessarily **way** easier, but surely neither way harder, such that I don't really see a benefit that would justify the programming effort required to implement the feature to be honest.

**Comment by w2sv** [comment]
And as to the second option, you could achieve this behavior by simply disabling the automatic data refreshing and not manually refreshing the data either, no? Besides, what would be a possible use case for displaying the details of a WiFi connection that doesn't even exist anymore?

**Comment by w2sv** [comment]
Closing for now.
