### ISSUE TITLE
[Bug] IPv6 ULA addresses are listed as GUA

### ISSUE THREAD

**Issue by GoetzGoerisch** [w2sv/WiFi-Widget#130]
### Overview

ULA and GUA addresses are mixed.

My test device currently has 2 ULA and 2 GUA addresses.
From each one is static and one is temporary.

In the widget the static ULA is also listed as GUA1
The temporary ULA is also listed as GUA4 

### How to reproduce

Launch Wifi-Widget in a IPv6 Network with SLAAC.

### Version

1.14.14

### Android Version

Android 11

### Device Model

Nokia 8.1

**Comment by w2sv** [comment]
How do you know the GUAs are actually ULAs? I'm currently considering addresses to be ULAs if they start either with "fc" or "fd" as per https://networklessons.com/ipv6/ipv6-address-types#Unique_Local. Maybe that's an incomplete definition though.

**Comment by GoetzGoerisch** [comment]
The ULA starts with `fdxx:` and the GUA with `2a02:` in my case.

ULA  definition is complete as per [RFC4193](https://datatracker.ietf.org/doc/html/rfc4193) 

I get listed in the widget:

```
IP-ULA1: fdxx::b135
IP-ULA2: fdxx::c91a
IP-GUA1: 2a02::f44
IP-GUA2: 2a02::c91a
IP-GUA3: fdxx::b135
IP-GUA4: fdxx::c91a
```
`About the telefon` lists the four addresses correctly.

Gateway, DHCP and DNS is currently empty due to #131

**Comment by w2sv** [comment]
Should be fixed in [1.5.0](https://github.com/w2sv/WiFi-Widget/releases/tag/1.5.0), please give it a try and let me know if it works.

**Comment by GoetzGoerisch** [comment]
Thank you!

**Comment by w2sv** [comment]
Thanks for reporting
