### ISSUE TITLE
[Feature Request] Enable display of the subnet mask corresponding to each IPv4 address

### ISSUE THREAD

**Issue by w2sv** [w2sv/WiFi-Widget#145]
### Overview

See above

**Comment by w2sv** [comment]
Added in [1.6.2](https://github.com/w2sv/WiFi-Widget/releases/tag/1.6.2).

**Comment by dmausner** [comment]
It is sufficient to show the netmask as ip/width without showing the 32 bit mask in a.b.c.d format.
The intention is to save space in the widget.
You may also consider making netmask an option.
