### ISSUE TITLE
[Feature Request] IP Location information, Auto Refresh 

### ISSUE THREAD

**Issue by RGBok** [w2sv/WiFi-Widget#151]
### Overview

The app is perfect! Exactly what I was looking for. Two things that can make it even better:
1. Auto refresh on network status change
2. Public IP Location Name (like what city it comes back to)
I use this app in conjunction with my VPNs and it's an easy way to confirm.

- Thank You

**Comment by freQniK** [comment]
I second this. It would be nice to know city, country since I use VPNs alot.  

You can fetch that json data from either:

* https://ifconfig.co
* http://ip-api.com/json

Also, add a bitcoin or monero address for donations please.

**Comment by w2sv** [comment]
Auto refresh ain't possible, google doesn't allow reacting to network changes while an app is in the background to prevent it from triggering down-/uploads upon an internet connection having been established.
IP location on the other hand I added in [1.6.0](https://github.com/w2sv/WiFi-Widget/releases/tag/1.6.0). I'm fetching it from https://ifconfig.co/ along with some other newly added properties, so thanks for the suggestion @freQniK :)
Thank you for the suggestion too, @RGBok. Let me know how it works for you
