### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [w2sv/WiFi-Widget#157]
### Overview

[1.5.03.apk.html.zip](https://github.com/user-attachments/files/17541315/1.5.03.apk.html.zip)

Not sure why. Can you try cleaning the cache and rebuilding the apk?

### How to reproduce

https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8203524078

### Version

1.5.03

### Android Version

13

### Device Model

Pixel 6

**Comment by w2sv** [comment]
Actually I'm already running a `./gradlew clean` before assembling the apk and uploading it, but alright. The baseline profile generation really creates problems time after time again...

**Comment by w2sv** [comment]
https://github.com/w2sv/WiFi-Widget/releases/tag/1.5.03.1

**Comment by linsui** [comment]
It's not fixed... https://gitlab.com/linsui/fdroiddata/-/jobs/8212055099

**Comment by licaon-kter** [comment]
confirmed locally thanks

**Comment by linsui** [comment]
It builds, thanks!

**Comment by w2sv** [comment]
Thank you
