### ISSUE TITLE
[Bug] Remove `DependencyInfoBlock`

### ISSUE THREAD

**Issue by licaon-kter** [w2sv/WiFi-Widget#161]
### Overview

ref: https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8260053788#L699

We find that there is a `DependencyInfoBlock` in your APK.

It's a [Frosting](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) block in the signing block.

It's added by AGP and signed by Google's public key so it can't be read by anyone else except Google.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

### How to reproduce

-

### Version

-

### Android Version

-

### Device Model

-

**Comment by w2sv** [comment]
Done: https://github.com/w2sv/WiFi-Widget/releases/tag/1.6.0.1

I suppose publishing to the playstore with it being disabled might lead to issues though?

**Comment by licaon-kter** [comment]
two ideas:
* other devs did not complain :shrug: 
* we don't care (for now lol) about bundles, so `includeInBundle = false` is not required :wink:
