### ISSUE TITLE
Some new properties result in SocketException

### ISSUE THREAD

**Issue by seniordevel** [w2sv/WiFi-Widget#164]
### Overview

Some properties not shown, instead socket exception is displayed.
See screenshot below.

Location permissions allowed.
Locazion service is on.

Android 11

![Screenshot_20241112-115248_1](https://github.com/user-attachments/assets/ffa5968c-fc4c-461b-a005-c61bd2b25111)

### How to reproduce

...

### Version

1.6.0.1

### Android Version

Android 11

### Device Model

Gigaset GS4

**Comment by seniordevel** [comment]
Caused by firewall, since those properties need internet access

**Comment by w2sv** [comment]
Yeah I deliberately made it so that the exception kind is displayed if there is one. I guess I could improve it by having it display something like "No internet connection" though, to make it clear to the user that that's the problem.
