### ISSUE TITLE
[Bug] Latest update changed max. width of content

### ISSUE THREAD

**Issue by andikay** [w2sv/WiFi-Widget#179]
### Overview

I use this widget in the size 3x1 (width x height) to display the SiteLocal IP (only v4, nothing else) and Link Speed. With the newest update something changed with the width of the content and the border on the right side. The local IP now takes up two rows, which looks terrible and ruins the usability of the widget. The font size is already set to the lowest possible in the settings.

Also, the space between the left column and the right column in general seems way too large, which prevents the widget from being used in a 2x1 size, which I would initially have preferred.

![Screenshot_2024-12-24-12-31-47-96_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/c94160bd-0156-406d-a0ec-2752fe9737d6)

### How to reproduce

Set the widget size to 3x1 and have IP SiteLocal v4 displayed.

### Version

1.6.2

### Android Version

Android 14

### Device Model

Realme GT 5G

**Comment by w2sv** [comment]
Fixed in [1.6.3](https://github.com/w2sv/WiFi-Widget/releases/tag/1.6.3).
