### ISSUE TITLE
Dark theme 

### ISSUE THREAD

**Issue by xmha97** [w2sv/WiFi-Widget#3]
Please add the dark theme to the settings page.

**Comment by seniorm0ment** [comment]
+1

**Comment by w2sv** [comment]
Has been implemented in version [1.1.3](https://github.com/w2sv/WiFi-Widget/releases/tag/1.1.3)

**Comment by xmha97** [comment]
Thanks

**Comment by xmha97** [comment]
My phone is dark.
Also I set the app theme to dark.
But the settings are still light:

![Screenshot_2023-02-07-05-17-03-084_com.w2sv.wifiwidget.jpg](https://user-images.githubusercontent.com/23485114/217127439-5ce562e1-a897-4544-a3da-d36a0e122b4c.jpg)

![Screenshot_2023-02-07-05-20-44-309_com.w2sv.wifiwidget.jpg](https://user-images.githubusercontent.com/23485114/217127492-4fbd7168-bbba-43b9-890b-af23bed598bf.jpg)

**Comment by w2sv** [comment]
Well yeah, the theme selected in the dialog applies only to the widget, the dialog is entitled 'Configure Widget', after all :)
I thought that's what you were requesting all along. 

I'm not quite sure how worthwhile it would be to make the in-app theme configurable, as it's only purpose is to pin a widget and possibly configure it, amounting to you normally spending next to no time on the screen.

**Comment by xmha97** [comment]
> Well yeah, the theme selected in the dialog applies only to the widget, the dialog is entitled 'Configure Widget', after all :)
> I thought that's what you were requesting all along. 
> 
> I'm not quite sure how worthwhile it would be to make the in-app theme configurable, as it's only purpose is to pin a widget and possibly configure it, amounting to you normally spending next to no time on the screen.

If you think it will take too much of your time, please close this issue.
