### ISSUE TITLE
Why does WiFi Widget need Internet access?

### ISSUE THREAD

**Issue by marek22k** [w2sv/WiFi-Widget#37]
Hello,

on https://f-droid.org/en/packages/com.w2sv.wifiwidget/ I have seen that WiFi widget has permission `have full network access`. Is this necessary? Why does WiFi Widget need internet access? Is the WiFi data not read locally?

**Comment by w2sv** [comment]
It's required by the java method `NetworkInterface.getNetworkInterfaces()`, which in turn is the only way I found to retrieve the networkPrefixLength and thereby construct the subnet mask. The permission is not used to open sockets or anything of the like.

Hence, the data is of course retrieved locally.

**Comment by marek22k** [comment]
Thanks for the answer!

**Comment by w2sv** [comment]
Sure, you're welcome.

**Comment by w2sv** [comment]
FYI: the Internet permission was removed in [1.2.51](https://github.com/w2sv/WiFi-Widget/releases/tag/1.2.51), as I've found a way to retrieve the network prefix length that doesn't depend on it.
