### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [w2sv/WiFi-Widget#44]
ref: https://monitor.f-droid.org/builds/log/com.w2sv.wifiwidget/29#site-footer

ref: https://github.com/w2sv/Compose-Color-Picker-Bundle/blob/1.0.0-rc8/colorpicker/build.gradle#L56

**Comment by w2sv** [comment]
Thank you for pointing that out, I've created a new release that should resolve the issue.

**Comment by licaon-kter** [comment]
Thanks

**Comment by licaon-kter** [comment]
another issue: https://gitlab.com/fdroid/fdroiddata/-/jobs/5734012604#L631

difflog: [wifi45.log](https://github.com/w2sv/WiFi-Widget/files/13648774/wifi45.log)

appears to be: https://gitlab.com/fdroid/fdroiddata/-/issues/3138 :(

**Comment by linsui** [comment]
Please update Compose Compiler to 1.5.6. See https://gitlab.com/fdroid/fdroiddata/-/issues/3138

**Comment by w2sv** [comment]
I just published version [1.4.02](https://github.com/w2sv/WiFi-Widget/releases), which uses compose compiler 1.5.7. Hopefully that'll fix it.

**Comment by licaon-kter** [comment]
@w2sv I don't see a new version :roll_eyes: https://github.com/w2sv/WiFi-Widget/blob/1.4.02/gradle.properties#L10-L11

**Comment by w2sv** [comment]
@licaon-kter Sorry, my bad. [1.4.03](https://github.com/w2sv/WiFi-Widget/releases/tag/1.4.03) actually features a new `gradle.properties` version this time around.

**Comment by linsui** [comment]
It's built, thanks!

**Comment by licaon-kter** [comment]
Hmm, another fail: https://gitlab.com/fdroid/fdroiddata/-/jobs/6169699117

will get diff log asap

**Comment by w2sv** [comment]
Seems like there's a problem with the [baseline profiles](https://github.com/w2sv/WiFi-Widget/tree/main/app/src/release/generated/baselineProfiles), the strange thing is only, that I had already added them in 1.4.04, which built successfully.

**Comment by licaon-kter** [comment]
the baseline files will be different when classes.dex are

here's the full diff: 
[w2sv50.log](https://github.com/w2sv/WiFi-Widget/files/14313219/w2sv50.log)

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/commit/05bce10a63dc558f03358afcbba14feac3687456

**Comment by w2sv** [comment]
> the baseline files will be different when classes.dex are
> 
> here's the full diff: [w2sv50.log](https://github.com/w2sv/WiFi-Widget/files/14313219/w2sv50.log)

So what can I do to resolve the issue? It sounds like you're saying that the baseline files don't match the .dex classes, however I've been recreating the baseline files before each release .apk build so that they reflect the latest changes. 

Actually I'm sort of considering to simply remove the baseline profiles once again, as they haven't brought any noticeable app startup speed gains whilst causing this build error.

**Comment by w2sv** [comment]
Thank you, for some reason the newest version (1.4.11) is still not online though 🤔

https://f-droid.org/en/packages/com.w2sv.wifiwidget/

**Comment by linsui** [comment]
It's a normal delay. Maybe it will be available in a week.

**Comment by w2sv** [comment]
Alright
