### ISSUE TITLE
Display BSSID

### ISSUE THREAD

**Issue by tobster** [w2sv/WiFi-Widget#53]
Would it be possible to display the base service set id currently in use? [See ](https://en.wikipedia.org/wiki/Service_set_%28802.11_network%29?wprov=sfla1)

**Comment by w2sv** [comment]
Ich habe gerade Version 1.2.61 veröffentlicht, welche die BSSID
unterstützt. Sollte spätestens in ein paar Stunden im PlayStore und morgen
bei FDroid online sein.

Am Mi., 19. Juli 2023 um 21:57 Uhr schrieb Tobias Hochwallner <
***@***.***>:

**Comment by tobster** [comment]
Wow that was fast. Thank you. Now I have to wait for f-droid.
