### ISSUE TITLE
[Feature Request] Themed / Monochrome app icon support

### ISSUE THREAD

**Issue by sebastien46** [w2sv/WiFi-Widget#54]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by w2sv** [comment]
I'm a bit swamped right now, but I'm always open for PRs.

**Comment by w2sv** [comment]
I added a monochromatic launcher icon in [1.3.04](https://github.com/w2sv/WiFi-Widget/releases/tag/1.3.04).
