### ISSUE TITLE
[Feature Request] Show public IPv4

### ISSUE THREAD

**Issue by Tatsh** [w2sv/WiFi-Widget#55]
Would be great.

**Comment by marek22k** [comment]
The "problem" with this is that this is not something that an app can just read. It would have to reach an external service like a STUN server for that.

**Comment by w2sv** [comment]
Yeah that's precisely why I hadn't yet incorporated it. I won't be able to accommodate its retrieval as easily into the general WiFi property retrieval process as I could do with the BSSID for that reason, but it should be feasible anyways. I'll see what I can do.

**Comment by w2sv** [comment]
I implemented it in [1.4.0](https://github.com/w2sv/WiFi-Widget/releases/tag/1.4.0). Please let me know what you think and close the issue if you're satisfied with the result.

**Comment by Tatsh** [comment]
Works great. Thanks
