### ISSUE TITLE
All fields stuck at "Loading..." since latest update.

### ISSUE THREAD

**Issue by d5xtgr** [w2sv/WiFi-Widget#56]
All fields in the widget display a dark grey "Loading..." instead of the intended information.  If I manually click to refresh, the timestamp updates, but no information is shown.

WiFi Widget version 1.2.73
LineageOS version 20 (Android version 13)
Essential PH-1

**Comment by w2sv** [comment]
Huh, strange. I'll try to replicate it using a couple of different device emulators. If however I don't encounter that issue thus, it'll be hard for me to pinpoint its source, as there doesn't seem to be an easily runnable LineageOS image out there.

**Comment by w2sv** [comment]
In fact, have you added a new widget since you've updated the app, or are you still using one you had already added on an older version? In case of the latter the new property updating service wouldn't be bound to the old widget anymore, which would explain that phenomenon.

**Comment by d5xtgr** [comment]
Yes, it was an old widget.  Replacing it with a new one has fixed the problem.  Thanks!
