### ISSUE TITLE
[Feature Request] Treat ULAs as local addresses and enable individual en-/disabling of address sub categories

### ISSUE THREAD

**Issue by w2sv** [w2sv/WiFi-Widget#59]
I get three IPv6 addresses - a link-local address (fe80::/10), a unique local address (fd00::/8) and a unique global address (2000::/3).  The link-local address always shows up as the "Local" one, but the unique local and unique global addresses sometimes switch between "public 1" and "public 2".  Could the addresses be sorted lexicographically before assigning them to "public 1" and "public 2" so that I can reliably see my global address without having to have both displayed?

_Originally posted by @d5xtgr in https://github.com/w2sv/WiFi-Widget/issues/21#issuecomment-1674069896_

**Comment by DocSniper** [comment]
ULA or fc00::/7 is not link-local but local.
As ULA says: unique local addresses

Private IPv6 addresses fc00::/7 are routed in the same way as private IPv4 addresses 10.0.0.0/8 and 172.16.0.0/16 and 192.168.0.0/24. Of course you can route fc00::/7 (or parts of it) on your own devices but they are not routed globally, therefore local.

See: https://en.wikipedia.org/wiki/Private_network#Private_IPv6_addresses

**Comment by w2sv** [comment]
So I'm envisioning to drop the macro distinction between IPv4 and IPv6, and replace it with a distinction between:

1. link-local (IPv4 & IPv6)
2. site-local (IPv4 & IPv6)
3. Unique local address (IPv6 only; fc00::/7) 
4. Global Unicast address (IPv6 only; 2000::/3)
5. Public (IPv4 & IPv6; the ones retrieved from https://api.ipify.org/)

These can respectively be disabled through the configuration dialog, and for those kinds that may be represented in IPv4 & IPv6 format, I'd also allow the disablement of either the IPv4 or IPv6 representation. 

Then I'd display them on the widget by enumerating addresses pertaining to the same IP category, like so:

_LinkLocal #1: ...
LinkLocal #2: ...
ULA #1
GUA #1
..._ 

Again, I wouldn't distinguish between IPv4 & IPv6 regarding the display of the different addresses at all, as one can infer whether it is one or the other by just looking at the address value. 

Please let me know if you in principal agree with this type of distinction, representation, the specific IP categories I chose, and/or if you see any room for improvement.

**Comment by DocSniper** [comment]
Hello @w2sv and yes, great suggestion. 
I would say we look at the changes during operation and then see whether it fits or whether adjustments would be good. 
Thanks in any case.

**Comment by marek22k** [comment]
I would also like to be able to turn the public IP off and on, so that a connection to a foreign server is not simply established.

Furthermore, there can be both a public IPv4 and a public IPv6 address.

**Comment by w2sv** [comment]
Implemented in [1.4.0](https://github.com/w2sv/WiFi-Widget/releases/tag/1.4.0). I also added **loopback** and **multicast** as separate categories. Let me know what you think.

**Comment by w2sv** [comment]
Alright, I'll take that as silent approval.

**Comment by d5xtgr** [comment]
I'm sorry - I never got the new version through F-Droid, and now due to circumstances beyond my control I no longer use Android at all.  Thanks for making the change!
