### ISSUE TITLE
Show device MAC

### ISSUE THREAD

**Issue by noahfriedman** [w2sv/WiFi-Widget#61]
Recent versions of android have an option to randomize the interface MAC as a privacy measure. It would be worth displaying the present value since this can be used e.g. to look up router and switch port state for connections.

Thanks

**Comment by w2sv** [comment]
Retrieving the randomized MAC address is reserved for Device Owner, Profile Owner, and Carrier apps only, none of which WiFi Widget could possibly be. Implementing that feature will therefore not be feasible.

[Reference](https://developer.android.com/reference/android/net/wifi/WifiConfiguration#getRandomizedMacAddress())
