### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Pr8or** [w2sv/WiFi-Widget#66]
Can not update; get message: "Error Installing WIFI Widget"

The privileged permissions  have not been granted to the extensions! Please create bug report.

So here it is what else do you need?

**Comment by w2sv** [comment]
Sounds like something stemming from your APK installer, in any case nothing I would have set up myself. Maybe try to completely uninstall and reinstall the app. If that doesn't do it attach some screenshots of the error message, maybe I can help you more that way.
