### ISSUE TITLE
Hide labels (instead of wrapping lines)

### ISSUE THREAD

**Issue by mcg-android** [w2sv/WiFi-Widget#80]
Screen space is scarce. :-)

I'm using a widget showing only SSID and link speed. If the labels ("SSID" and "Link Speed") weren't there, the widget would only take up half the space.

Personally, I'd be truly happy with a switch allowing to turn off the labels. But maybe the labels could automatically get hidden instead of wrapping lines, i.e. when running out of horizontal space?

**Comment by w2sv** [comment]
Would you mind attaching a screenshot of the widget as it is now? I have issues imagining how removing the labels of those two properties would save screen space. Either you're for some reason able to make the widget slimmer than it's supposed to be, or your SSID is just absurdly long :D
