### ISSUE TITLE
IPv4 Local Showing Incorrect IP Address & Subnet

### ISSUE THREAD

**Issue by Hyperthread** [w2sv/WiFi-Widget#84]
IPv4 local address is showing an incorrect address. The widget is showing 10.0.0.2/32 instead of the correct IP address of 10.0.0.14/24.

My phone is a SM-975u.

**Comment by w2sv** [comment]
Are you sure the data was refreshed before you did the comparison? The IP Addresses are displayed just the way they are retrieved from the [ConnectivityManager](https://developer.android.com/reference/android/net/ConnectivityManager), that is, from the Android Sdk itself. The app is not mutating them in any way. Also, I recommend updating the app, the 'local' IP category has been dropped as of 1.4.0.
