### ISSUE TITLE
Public IP Broken

### ISSUE THREAD

**Issue by f1vefour** [w2sv/WiFi-Widget#97]
When Public IP is checked and IPv6 is disabled the widget still shows both the IPv6 and IPv4 addresses, the same if IPv6 is checked and IPv4 is unchecked both are still shown.

This feature is currently broken.

**Comment by w2sv** [comment]
Yeah, I was able to reproduce it. Thanks for reporting, I'll look into it.

**Comment by w2sv** [comment]
Should be fixed in [1.4.05](https://github.com/w2sv/WiFi-Widget/releases/tag/1.4.05), let me know if it works for you.

**Comment by f1vefour** [comment]
It's fixed, thanks for the quick resolution. Closing.

**Comment by w2sv** [comment]
You're welcome :)
