### ISSUE TITLE
removing all "Buttons" options still makes a bar that blocks data on the widget 

### ISSUE THREAD

**Issue by Indysaurus** [w2sv/WiFi-Widget#99]
Hello,
If all the checks are removed under the buttons section, there is still a bar. This can block data from being displayed depending on number of lines. In my case 3 lines. With my current setup I either have to have a large excessive block on the bottom or small widget with scroll bar and small block on the bottom. This is on Samsung 24 ultra android v14, one UI v6.1, app v1.4.04. 
Maybe this is more suggestion than bug but maybe this bar should go hidden if all deselected. Thanks for the app :)
![Screenshot_20240211_160916_Nova7](https://github.com/w2sv/WiFi-Widget/assets/114551509/9b040f4e-a8ad-461c-977a-733809134fb5)
![Screenshot_20240211_160851_Nova7](https://github.com/w2sv/WiFi-Widget/assets/114551509/0f2f3baf-c588-4ad4-8414-265f4a98d9da)
![Screenshot_20240211_160736_WiFi Widget](https://github.com/w2sv/WiFi-Widget/assets/114551509/b2d4032e-001c-4675-b514-395c56d1065f)

**Comment by w2sv** [comment]
Good point, I will look into it. Shouldn't be too hard to implement.

**Comment by w2sv** [comment]
Implemented in [1.4.06](https://github.com/w2sv/WiFi-Widget/releases/tag/1.4.06). I also merged the 'buttons' section and the 'last refresh time display' to a 'bottom row', makes more sense that way imo. Let me know what you think. Thanks for the suggestion!

**Comment by Indysaurus** [comment]
Looks good to me thanks!

**Comment by w2sv** [comment]
Great, my pleasure
